import type { Producto } from "./types";

/**
 * Catálogo semilla — los 41 productos reales del market, leídos de los envases
 * de las fotos que pasó el cliente.
 *
 * ⚠️ LOS PRECIOS SON INVENTADOS. El cliente pasó la lista de productos sin
 * precios. Son verosímiles a propósito para que la demo se vea real; se cargan
 * los reales desde el panel. Lo mismo vale para `stock`: son números elegidos
 * para que la demo muestre las tres situaciones (normal, últimas unidades,
 * agotado).
 *
 * Este archivo es la fuente de verdad mientras no haya Supabase configurado,
 * y también el script de carga inicial cuando lo haya (supabase/seed.sql).
 */
export const PRODUCTOS_SEED: Producto[] = [
  // ── Galletitas ────────────────────────────────────────────────────────────
  {
    id: "schar-choco-chip-cookies",
    nombre: "Choco Chip Cookies",
    marca: "Schär",
    descripcion: "Galletitas con chips de chocolate. El clásico de la góndola.",
    categoria: "galletitas",
    imagen: "/productos/schar-choco-chip-cookies.jpg",
    precio: 7400,
    unidad: "200 g",
    stock: 18,
    reservado: 0,
    stockMinimo: 4,
    destacado: true,
    activo: true,
    orden: 1,
  },
  {
    id: "oreo-sin-gluten",
    nombre: "Oreo Sin Gluten",
    marca: "Oreo",
    descripcion: "Las de siempre, ahora aptas. Relleno sabor vainilla.",
    categoria: "galletitas",
    imagen: "/productos/oreo-sin-gluten.jpg",
    precio: 3400,
    unidad: "95 g",
    stock: 24,
    reservado: 0,
    stockMinimo: 6,
    destacado: true,
    activo: true,
    orden: 2,
  },
  {
    id: "schar-wafers-vainilla",
    nombre: "Wafers alla Vaniglia",
    marca: "Schär",
    descripcion: "Obleas rellenas de crema de vainilla.",
    categoria: "galletitas",
    imagen: "/productos/schar-wafers-vainilla.jpg",
    precio: 4800,
    unidad: "125 g",
    stock: 12,
    reservado: 0,
    stockMinimo: 4,
    destacado: false,
    activo: true,
    orden: 3,
  },
  {
    id: "schar-mini-sorrisi",
    nombre: "Mini Sorrisi",
    marca: "Schär",
    descripcion: "Galletitas de cacao rellenas con 33% de crema de leche.",
    categoria: "galletitas",
    imagen: "/productos/schar-mini-sorrisi.jpg",
    precio: 5600,
    unidad: "100 g",
    stock: 9,
    reservado: 0,
    stockMinimo: 4,
    destacado: false,
    activo: true,
    orden: 4,
  },
  {
    id: "schar-snack-chocolate",
    nombre: "Snack Milk Chocolate",
    marca: "Schär",
    descripcion: "Obleas con avellanas bañadas en chocolate con leche. Pack x3.",
    categoria: "galletitas",
    imagen: "/productos/schar-snack-chocolate.jpg",
    precio: 5200,
    unidad: "105 g · 3 u.",
    stock: 3,
    reservado: 0,
    stockMinimo: 4,
    destacado: false,
    activo: true,
    orden: 5,
  },
  {
    id: "kapac-vainillas",
    nombre: "Vainillas",
    marca: "Kapac",
    descripcion: "Para el café con leche o para armar un postre.",
    categoria: "galletitas",
    imagen: "/productos/kapac-vainillas.jpg",
    precio: 3900,
    unidad: "200 g",
    stock: 15,
    reservado: 0,
    stockMinimo: 4,
    destacado: false,
    activo: true,
    orden: 6,
  },
  {
    id: "angiola-limon-chocolate",
    nombre: "Galletitas de limón bañadas en chocolate",
    marca: "Angiola",
    descripcion: "Sabor limón con baño de chocolate.",
    categoria: "galletitas",
    imagen: "/productos/angiola-limon-chocolate.jpg",
    precio: 6200,
    unidad: "130 g",
    stock: 7,
    reservado: 0,
    stockMinimo: 3,
    destacado: false,
    activo: true,
    orden: 7,
  },
  {
    id: "celienergy-cacao-mani",
    nombre: "Galletitas de cacao y maní",
    marca: "Celienergy",
    descripcion: "Con harina de maní.",
    categoria: "galletitas",
    imagen: "/productos/celienergy-cacao-mani.jpg",
    precio: 3700,
    unidad: "130 g",
    stock: 14,
    reservado: 0,
    stockMinimo: 4,
    destacado: false,
    activo: true,
    orden: 8,
  },
  {
    id: "doninas-chia-limon",
    nombre: "Galletitas de chía y limón",
    marca: "Doninas",
    descripcion: "Sin azúcar agregada, con esencia natural de limón y stevia.",
    categoria: "galletitas",
    imagen: "/productos/doninas-chia-limon.jpg",
    precio: 4100,
    unidad: "150 g",
    stock: 11,
    reservado: 0,
    stockMinimo: 4,
    destacado: false,
    activo: true,
    orden: 9,
  },
  {
    id: "doninas-amapola-naranja",
    nombre: "Galletitas de amapola y naranja",
    marca: "Doninas",
    descripcion: "Sin azúcar agregada.",
    categoria: "galletitas",
    imagen: "/productos/doninas-amapola-naranja.jpg",
    precio: 4100,
    unidad: "150 g",
    stock: 10,
    reservado: 0,
    stockMinimo: 4,
    destacado: false,
    activo: true,
    orden: 10,
  },
  {
    id: "rraac-rellenas-chocolate",
    nombre: "Galletitas rellenas de chocolate",
    marca: "Rraac",
    descripcion: "Tapas de vainilla con relleno sabor chocolate. 100% vegetal.",
    categoria: "galletitas",
    imagen: "/productos/rraac-rellenas-chocolate.jpg",
    precio: 3200,
    unidad: "90 g",
    stock: 16,
    reservado: 0,
    stockMinimo: 4,
    destacado: false,
    activo: true,
    orden: 11,
  },
  {
    id: "snuks-almohaditas-frutilla",
    nombre: "Almohaditas rellenas de frutilla",
    marca: "Snuks",
    descripcion: "Para el desayuno o para picar.",
    categoria: "galletitas",
    imagen: "/productos/snuks-almohaditas-frutilla.jpg",
    precio: 2600,
    unidad: "50 g",
    stock: 0,
    reservado: 0,
    stockMinimo: 4,
    destacado: false,
    activo: true,
    orden: 12,
  },

  // ── Alfajores ─────────────────────────────────────────────────────────────
  {
    id: "dantelli-alfajor-ddl",
    nombre: "Alfajor de dulce de leche",
    marca: "Dantelli",
    descripcion: "Relleno de dulce de leche con baño de chocolate semiamargo.",
    categoria: "alfajores",
    imagen: "/productos/dantelli-alfajor-ddl.jpg",
    precio: 1900,
    unidad: "50 g",
    stock: 32,
    reservado: 0,
    stockMinimo: 8,
    destacado: true,
    activo: true,
    orden: 20,
  },
  {
    id: "dantelli-ddl-mousse-x3",
    nombre: "Alfajor triple dulce de leche y mousse de vainilla",
    marca: "Dantelli",
    descripcion: "Tres capas. Dulce de leche y mousse de vainilla.",
    categoria: "alfajores",
    imagen: "/productos/dantelli-ddl-mousse-x3.jpg",
    precio: 4500,
    unidad: "100 g",
    stock: 13,
    reservado: 0,
    stockMinimo: 4,
    destacado: false,
    activo: true,
    orden: 21,
  },
  {
    id: "smams-alfajor-ddl",
    nombre: "Alfajor con dulce de leche",
    marca: "Smams",
    descripcion: "Baño de repostería semiamargo.",
    categoria: "alfajores",
    imagen: "/productos/smams-alfajor-ddl.jpg",
    precio: 1700,
    unidad: "50 g",
    stock: 28,
    reservado: 0,
    stockMinimo: 8,
    destacado: false,
    activo: true,
    orden: 22,
  },
  {
    id: "smams-alfajor-triple",
    nombre: "Alfajor triple",
    marca: "Smams",
    descripcion: "Triple, con mousse y dulce de leche.",
    categoria: "alfajores",
    imagen: "/productos/smams-alfajor-triple.jpg",
    precio: 2900,
    unidad: "unidad",
    stock: 19,
    reservado: 0,
    stockMinimo: 6,
    destacado: false,
    activo: true,
    orden: 23,
  },
  {
    id: "lulemuu-alfajor-arroz",
    nombre: "Alfajor de arroz con dulce de leche",
    marca: "Lulemuu",
    descripcion: "Liviano, de galleta de arroz. Ideal para la mochila.",
    categoria: "alfajores",
    imagen: "/productos/lulemuu-alfajor-arroz.jpg",
    precio: 1500,
    unidad: "26 g",
    stock: 41,
    reservado: 0,
    stockMinimo: 10,
    destacado: true,
    activo: true,
    orden: 24,
  },

  // ── Barritas ──────────────────────────────────────────────────────────────
  {
    id: "crudda-brownie",
    nombre: "Crudda Bar Brownie",
    marca: "Crudda",
    descripcion:
      "Proteína de arveja, quinoa, pasta de maní y cacao. Sin conservantes.",
    categoria: "barritas",
    imagen: "/productos/crudda-brownie.jpg",
    precio: 3600,
    unidad: "40 g",
    stock: 22,
    reservado: 0,
    stockMinimo: 6,
    destacado: true,
    activo: true,
    orden: 30,
  },
  {
    id: "crudda-peanut-caramel",
    nombre: "Crudda Bar Peanut Caramel",
    marca: "Crudda",
    descripcion: "9 g de proteína y 7 g de fibra. A base de plantas.",
    categoria: "barritas",
    imagen: "/productos/crudda-peanut-caramel.jpg",
    precio: 3600,
    unidad: "40 g",
    stock: 20,
    reservado: 0,
    stockMinimo: 6,
    destacado: false,
    activo: true,
    orden: 31,
  },
  {
    id: "crudda-arandanos-nuez",
    nombre: "Crudda Bar Arándanos y Nuez",
    marca: "Crudda",
    descripcion: "Con baño de repostería sabor arándanos.",
    categoria: "barritas",
    imagen: "/productos/crudda-arandanos-nuez.jpg",
    precio: 3600,
    unidad: "40 g",
    stock: 5,
    reservado: 0,
    stockMinimo: 6,
    destacado: false,
    activo: true,
    orden: 32,
  },
  {
    id: "bravisima-barra-proteica",
    nombre: "Bravísima y Proteica",
    marca: "Bravísima",
    descripcion:
      "15 g de proteína. Proteína de arveja, dátiles y chocolate semiamargo.",
    categoria: "barritas",
    imagen: "/productos/bravisima-barra-proteica.jpg",
    precio: 4900,
    unidad: "58 g",
    stock: 17,
    reservado: 0,
    stockMinimo: 5,
    destacado: false,
    activo: true,
    orden: 33,
  },
  {
    id: "merlin-bars-cafe-protein",
    nombre: "Merlín Bars Café Protein",
    marca: "Merlín Bars",
    descripcion:
      "16 g de proteína vegetal, dátiles, almendras, castañas de cajú y café.",
    categoria: "barritas",
    imagen: "/productos/merlin-bars-cafe-protein.jpg",
    precio: 4700,
    unidad: "55 g",
    stock: 14,
    reservado: 0,
    stockMinimo: 5,
    destacado: false,
    activo: true,
    orden: 34,
  },
  {
    id: "emm-fit-bar-mani",
    nombre: "emm! Fit Bar Maní",
    marca: "emm!",
    descripcion: "Barrita de maní para media mañana.",
    categoria: "barritas",
    imagen: "/productos/emm-fit-bar-mani.jpg",
    precio: 2800,
    unidad: "45 g",
    stock: 26,
    reservado: 0,
    stockMinimo: 6,
    destacado: false,
    activo: true,
    orden: 35,
  },
  {
    id: "mudra-armonia",
    nombre: "Mudra Armonía",
    marca: "Mudra",
    descripcion: "Arándanos, nueces y canela. Endulzada con miel.",
    categoria: "barritas",
    imagen: "/productos/mudra-armonia.jpg",
    precio: 2400,
    unidad: "35 g",
    stock: 23,
    reservado: 0,
    stockMinimo: 6,
    destacado: false,
    activo: true,
    orden: 36,
  },
  {
    id: "mudra-bienestar",
    nombre: "Mudra Bienestar",
    marca: "Mudra",
    descripcion: "Manzana, arándanos y jengibre. Sin azúcar agregada.",
    categoria: "barritas",
    imagen: "/productos/mudra-bienestar.jpg",
    precio: 2600,
    unidad: "40 g",
    stock: 21,
    reservado: 0,
    stockMinimo: 6,
    destacado: false,
    activo: true,
    orden: 37,
  },
  {
    id: "johnnys-barra-caju",
    nombre: "Barra de frutos secos con castañas de cajú",
    marca: "Johnny's Market",
    descripcion: "Con azúcar orgánica. Sin aditivos ni conservantes.",
    categoria: "barritas",
    imagen: "/productos/johnnys-barra-caju.jpg",
    precio: 3300,
    unidad: "30 g",
    stock: 12,
    reservado: 0,
    stockMinimo: 5,
    destacado: false,
    activo: true,
    orden: 38,
  },
  {
    id: "laddubar-gold-almendras",
    nombre: "Laddubar Gold Almendras",
    marca: "Laddubar",
    descripcion: "Dátiles, almendras y cacao. Raw y vegana.",
    categoria: "barritas",
    imagen: "/productos/laddubar-gold-almendras.jpg",
    precio: 2700,
    unidad: "30 g",
    stock: 18,
    reservado: 0,
    stockMinimo: 5,
    destacado: false,
    activo: true,
    orden: 39,
  },
  {
    id: "food-alchimist-trufa-datiles",
    nombre: "Trufa de dátiles y maní",
    marca: "The Food Alchimist",
    descripcion: "A base de dátiles y frutos secos. Kosher.",
    categoria: "barritas",
    imagen: "/productos/food-alchimist-trufa-datiles.jpg",
    precio: 1800,
    unidad: "20 g",
    stock: 30,
    reservado: 0,
    stockMinimo: 8,
    destacado: false,
    activo: true,
    orden: 40,
  },

  // ── Snacks ────────────────────────────────────────────────────────────────
  {
    id: "mani-king-salado",
    nombre: "Maní salado sin piel",
    marca: "Maní King",
    descripcion: "100% maní alto oleico. Para compartir.",
    categoria: "snacks",
    imagen: "/productos/mani-king-salado.jpg",
    precio: 6800,
    unidad: "350 g",
    stock: 16,
    reservado: 0,
    stockMinimo: 4,
    destacado: true,
    activo: true,
    orden: 50,
  },
  {
    id: "mani-king-tostado",
    nombre: "Maní tostado sin piel",
    marca: "Maní King",
    descripcion: "Sin sodio. 100% maní alto oleico.",
    categoria: "snacks",
    imagen: "/productos/mani-king-tostado.jpg",
    precio: 6800,
    unidad: "350 g",
    stock: 13,
    reservado: 0,
    stockMinimo: 4,
    destacado: false,
    activo: true,
    orden: 51,
  },
  {
    id: "mani-king-limon-pimienta",
    nombre: "Maní sabor limón y pimienta",
    marca: "Maní King",
    descripcion: "De la línea Chef.",
    categoria: "snacks",
    imagen: "/productos/mani-king-limon-pimienta.jpg",
    precio: 2200,
    unidad: "80 g",
    stock: 27,
    reservado: 0,
    stockMinimo: 6,
    destacado: false,
    activo: true,
    orden: 52,
  },
  {
    id: "schar-grissini",
    nombre: "Grissini",
    marca: "Schär",
    descripcion: "Crocantes y friables. Tres paquetes individuales.",
    categoria: "snacks",
    imagen: "/productos/schar-grissini.jpg",
    precio: 6100,
    unidad: "150 g · 3 u.",
    stock: 11,
    reservado: 0,
    stockMinimo: 4,
    destacado: true,
    activo: true,
    orden: 53,
  },
  {
    id: "lennys-pita-chips-sal",
    nombre: "Pita Chips sal marina",
    marca: "Lenny's",
    descripcion: "Ultrafinas y horneadas.",
    categoria: "snacks",
    imagen: "/productos/lennys-pita-chips-sal.jpg",
    precio: 4300,
    unidad: "100 g",
    stock: 8,
    reservado: 0,
    stockMinimo: 4,
    destacado: false,
    activo: true,
    orden: 54,
  },
  {
    id: "carilo-grisines-arvejas",
    nombre: "Mini grisines de arroz sabor arvejas",
    marca: "Productos Cariló",
    descripcion: "Extruido de harina de arveja y harina de arroz.",
    categoria: "snacks",
    imagen: "/productos/carilo-grisines-arvejas.jpg",
    precio: 3100,
    unidad: "100 g",
    stock: 15,
    reservado: 0,
    stockMinimo: 4,
    destacado: false,
    activo: true,
    orden: 55,
  },
  {
    id: "crisppino-minis-jamon",
    nombre: "Crisppino Minis sabor jamón",
    marca: "Crisppino",
    descripcion: "Snacks de arroz salados.",
    categoria: "snacks",
    imagen: "/productos/crisppino-minis-jamon.jpg",
    precio: 2300,
    unidad: "50 g",
    stock: 2,
    reservado: 0,
    stockMinimo: 5,
    destacado: false,
    activo: true,
    orden: 56,
  },

  // ── Pastas ────────────────────────────────────────────────────────────────
  {
    id: "dona-rosa-tirabuzon",
    nombre: "Tirabuzón",
    marca: "Doña Rosa",
    descripcion: "Pastas de maíz y arroz. Fideos secos al huevo.",
    categoria: "pastas",
    imagen: "/productos/dona-rosa-tirabuzon.jpg",
    precio: 4900,
    unidad: "500 g",
    stock: 20,
    reservado: 0,
    stockMinimo: 5,
    destacado: true,
    activo: true,
    orden: 60,
  },
  {
    id: "dona-rosa-tirabuzon-multivegetal",
    nombre: "Tirabuzón multivegetal",
    marca: "Doña Rosa",
    descripcion: "Tricolor, de maíz y arroz.",
    categoria: "pastas",
    imagen: "/productos/dona-rosa-tirabuzon-multivegetal.jpg",
    precio: 5400,
    unidad: "500 g",
    stock: 14,
    reservado: 0,
    stockMinimo: 5,
    destacado: false,
    activo: true,
    orden: 61,
  },
  {
    id: "dona-rosa-multivegetales",
    nombre: "Fideos secos multivegetales",
    marca: "Doña Rosa",
    descripcion: "Cintas de maíz y arroz.",
    categoria: "pastas",
    imagen: "/productos/dona-rosa-multivegetales.jpg",
    precio: 4700,
    unidad: "400 g",
    stock: 9,
    reservado: 0,
    stockMinimo: 5,
    destacado: false,
    activo: true,
    orden: 62,
  },
  {
    id: "blue-patna-coditos",
    nombre: "Coditos de arroz",
    marca: "Blue Patna",
    descripcion: "Pastas secas de harina de arroz con huevo.",
    categoria: "pastas",
    imagen: "/productos/blue-patna-coditos.jpg",
    precio: 4200,
    unidad: "500 g",
    stock: 22,
    reservado: 0,
    stockMinimo: 5,
    destacado: false,
    activo: true,
    orden: 63,
  },
  {
    id: "blue-patna-mostacholes",
    nombre: "Mostacholes de arroz",
    marca: "Blue Patna",
    descripcion: "Pastas secas de harina de arroz con huevo.",
    categoria: "pastas",
    imagen: "/productos/blue-patna-mostacholes.jpg",
    precio: 4200,
    unidad: "500 g",
    stock: 19,
    reservado: 0,
    stockMinimo: 5,
    destacado: false,
    activo: true,
    orden: 64,
  },
  {
    id: "soyarroz-fideos-espinaca",
    nombre: "Fideos de arroz con espinaca",
    marca: "Soyarroz",
    descripcion: "Tipo fideo seco, a base de arroz.",
    categoria: "pastas",
    imagen: "/productos/soyarroz-fideos-espinaca.jpg",
    precio: 3900,
    unidad: "300 g",
    stock: 10,
    reservado: 0,
    stockMinimo: 5,
    destacado: false,
    activo: true,
    orden: 65,
  },
];
